name: apicuron-on-commit
description: This action will report to APICURON on every push
author: Unipd

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  APICURON_ENDPOINT:
    description: 'API endpoint URL'
    required: true
  APICURON_TOKEN:
    description: 'API authentication token'
    required: true
# Define your outputs here.
outputs:
  reports:
    description: JSON array of activity logs

runs:
  using: node20
  main: dist/index.js
