name: Commit Context

on:
  push:
    branches:
      - main
      - dev
      - debug

jobs:
  get-commit-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to APICURON
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APICURON_ENDPOINT: 'https://www.apicuron.org/api/reports'
          APICURON_TOKEN: ${{ secrets.APICURON_TOKEN }}
